### ISSUE TITLE
Feat: 바텀 네비게이션 UI 개발 [NB-30]

### ISSUE THREAD

**Issue by sjsjsj1246** [Endless-Creation-32nd/refri_Mobile#3]
## Description

- 바텀 네비게이션 UI를 제작합니다.

## Todo

- [ ] 바텀 네비게이션 구성
- [ ] 네비게이션 스크린 구성
- [ ] + 버튼 레이아웃 구성
